version: '3'
services:
  ivy:
    build: .
    environment:
      - PATH=/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - ./ivy:/home/user/ivy
      - /home/nano/Documents/ivy-proofs/liveness/:/home/user/liveness
      # add more volumes as needed
    command: /bin/bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t
